name: CI

on:
  pull_request:
  push:
    branches-ignore:
      - gh-pages
    tags-ignore:
      - v*.*.*

jobs:

  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 16
            scala: 2
          - java: 11
            scala: 3
    name: Scala v${{ matrix.scala }} / Java v${{ matrix.java }}
    steps:

      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup Scala
        uses: japgolly/setup-everything-scala@v3.1
        with:
          java-version: adopt@1.${{ matrix.java }}
          jsdom-version: 22.1.0
          node-version: 19.9.0

      - name: Build and test
        shell: bash
        run: >-
          sbt++field scala${{ matrix.scala }}
          -J-Xmx3G
          -J-XX:+UseG1GC
          -DCI=1
          clean test ghpages/laikaSite
